### ISSUE TITLE
Warning in Metro Build

### ISSUE THREAD

**Issue by Harkindey** [jkroso/normalize-svg-path#10]
warn Package normalize-svg-path has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in ..../node_modules/normalize-svg-path/package.json

**Comment by gpbaculio** [comment]
also having this

**Comment by fukemy** [comment]
any solution please??

**Comment by dy** [comment]
It seems you're using rollup or some bundler that throws this error. That issue belongs there, here's nothing particular that needs to be exported in package.json.
I highly recommend to either ditch bundling or use esbuild. Everything else will drag you into such issues.
(Generally bundlers requiring ecosystem to change to fit their needs is unethical).
