### ISSUE TITLE
Close command left out of normalized path

### ISSUE THREAD

**Issue by neslho** [jkroso/normalize-svg-path#11]
Is it expected that the close path command is omitted when normalizing path data?

Running the script shown in the README you can see the `Z` is left off. 

![no-close-path](https://user-images.githubusercontent.com/2502374/126544511-7228b82a-f41d-426f-99f4-f54501b7d7d5.png)

Running the same script with just converting the path data to absolute points you can see the `Z` close path command is included.

![abs-close-path](https://user-images.githubusercontent.com/2502374/126544591-1fa377ba-5b29-4d40-939f-401954f7185d.png)

**Comment by dy** [comment]
Yes, that's by intent
