### ISSUE TITLE
Wrong normalization of arc command

### ISSUE THREAD

**Issue by dy** [jkroso/normalize-svg-path#2]
Say we have `M 10 10A 15 15 0 1 0 25 5Z`, which looks as 
![image](https://user-images.githubusercontent.com/300067/28482705-934bc798-6e37-11e7-9ebc-741f0106b82b.png)

After we normalize, we get `M 10 10C 2.6150075366704613 18.87666714763482 7.608661308541146 32.4190729673544 18.98857679099642 34.376330473536996C 30.368492273451693 36.33358797971959 39.59973285261361 25.237754045176068 35.604809833487884 14.40382939135866C 35.604809833487884 14.40382939135866 10 10 10 10`, which looks as
![image](https://user-images.githubusercontent.com/300067/28482730-b2042b12-6e37-11e7-9258-baa3c1b3e0d4.png)

**Comment by dy** [comment]
@jkroso just wonder if you consider a pull request or it is better for me to make a fork with different name? I managed to sort this out by https://github.com/colinmeinke/svg-arc-to-cubic-bezier/issues/1, but it takes updating tests/infrastructure a bit in this component.

**Comment by dy** [comment]
@jkroso if you don't feel like dealing with that, I can take care of updating. 
@colinmeinke resolved the issue https://github.com/colinmeinke/svg-arc-to-cubic-bezier/issues/1

Just `npm owner add dfcreative normalize-svg-path`

**Comment by jkroso** [comment]
Ok I'll let you sort it out since it could probably use a general update anyway. I've add you on npm and github

**Comment by dy** [comment]
Fixed in #3
