### ISSUE TITLE
arcToCurve is not a function

### ISSUE THREAD

**Issue by bpetetot** [jkroso/normalize-svg-path#4]
Hi,
I'm using your lib through svg-path-bounds lib, and I'm facing an issue with path containing arcs.
`
arcToCurve is not a function
`

I guess it's due to this commit https://github.com/jkroso/normalize-svg-path/commit/5eecf88b60735ba7fe8e9c0acba5af82dc2bd2d0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

You should keep the `.default` when your require `svg-arc-to-cubic-bezier`

**Comment by etgryphon** [comment]
Bump.

**Comment by dy** [comment]
Fixed as ESM entry in v1.1.0
