### ISSUE TITLE
Using π for pi problematic with at least browserify

### ISSUE THREAD

**Issue by Sairony** [jkroso/normalize-svg-path#8]
By default a <script> tag doesn't interpret src as unicode, therefor using π fails with unexpected token. It can be resolved by specifying charset, but overall I don't know if it's worth it to require unicode support just for 1 symbol.

**Comment by dy** [comment]
What π do you mean? Can you reference the code?

**Comment by Sairony** [comment]
It was my error, I'm using another library which depends on this one, but it's referencing version 0.1.0, which contains an arc function using π.
